"use client";

import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { useState } from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Navbar from "@/components/Navbar";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [queryClient] = useState(() => new QueryClient());
  const pathname = usePathname();

  // Mock user data - replace with actual user data from your auth system
  const mockUser = {
    name: "John Doe",
    role: "Student",
    imageUrl: "/default-avatar.svg",
  };

  const hideNavbar = pathname === "/auth/signin" || pathname === "/auth/signup";

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <QueryClientProvider client={queryClient}>
          {!hideNavbar && <Navbar user={mockUser} />}
          <main className="flex-1">{children}</main>
          <Toaster />
        </QueryClientProvider>
      </body>
    </html>
  );
}
